# Generated by Django 4.2.2 on 2023-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Full name', False), ('Job', False), ('Email', False), ('Integer', True), ('Date', False)], max_length=255)),
                ('from_field', models.IntegerField()),
                ('to_field', models.IntegerField()),
                ('order', models.CharField(max_length=255)),
                ('delete', models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='delete')),
            ],
        ),
        migrations.CreateModel(
            name='DataSchemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('modified', models.DateField(auto_now=True)),
                ('actions', models.CharField(max_length=255)),
            ],
        ),
    ]
