# Generated by Django 4.2.2 on 2023-06-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSV_converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'Full name'), ('2', 'Job'), ('3', 'Email'), ('4', 'Integer'), ('5', 'Date')], max_length=255)),
                ('order', models.CharField(max_length=255)),
                ('delete', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_separator', models.CharField(max_length=255)),
                ('string_character', models.CharField(max_length=255)),
                ('modified', models.DateField(auto_now=True)),
                ('actions', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Columns',
        ),
        migrations.DeleteModel(
            name='DataSchemas',
        ),
        migrations.AddField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSV_converter.schema'),
        ),
    ]
