# Generated by Django 4.2.3 on 2023-07-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSV_converter', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='name',
            new_name='schema_name',
        ),
    ]
